<?php

/**
 * Created by PhpStorm.
 * User: alex
 * Date: 13.09.15
 * Time: 22:32
 */
class C_Login extends Controller
{
  /**
   * Задает начальную работу контролёра, а именно:
   * - получение псетителя по заданным элементам(сессия, кука, БД)
   * - обновление активности посетителя в БД
   */
  public function onStart()
  {
    //parent::onStart(); // TODO: Change the autogenerated stub
    // пришол извне - очистить хвосты и всякие куки
    if ($_SERVER['REQUEST_METHOD'] === 'GET') {
      print_r($_GET);
      // если задан сид - есть текущая сессия.
      // уничтожить метки сессии, удалить данные в таблице активностей `online`
      if ($this->_sid)
        $this->stopActivity();

      // если задан логин - существует кука
      // присвоить куке просроченную дату
      if ($this->_login) {
        setcookie('login', $this->_login, time() - 10000);
        setcookie('password', $this->_password, time() - 10000);
      }
      $this->_right_to_view_this_page = 1;
    }
  }

  /**
   *
   */
  public function onEnd()
  {
    $this->_errorMessage = '';
    $login = '';
    // отослал форму - ждёт ответа
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
      print_r($_POST);
      $login = $_POST['login'];
      $password = $_POST['password'];

      // попробуем определить uid, если получится:
      // генерируем sid - метку сессии
      // создадим запись в таблице активностей online по sid и uid
      // создадим сессию $_SESSION['sid'] = sid;
      // переправим посетителя на главную страницу.
      $this->_user = $this->_mechanic->getUserByLogin($login);
      // есть посетитель!!
      if ($this->_user) {
        //print_r($this->_user);
        //необходим $_sid - генерируем!!
        //создаём запись в таблице активностей online по sid и uid
        if($this->runActivity()){
          // ЗАПИСЬ В ТАБЛИЦУ АКТИВНОСТЕЙ ВНЕСЕНА:
          // создаем куку (если флаг в форме "ЗАПОМНИТЬ")
          // переходим на главную страницу
          header('Location: index.php');
          exit();
        }
      }
      // что-то не так - неверный пароль/логин - вернуть форму
      // удалив возможные сессию и запись в таблице активностей
      $this->_errorMessage = 'Что-то пошлО не так, не удалось создать сессию. Приношу свои извинения!..';
      $login = $_POST['login'];
      if ($this->_sid)
        $this->stopActivity();
      if ($this->_login) {
        setcookie('login', $this->_login, time() - 10000);
        setcookie('password', $this->_password, time() - 10000);
      }
    }

    // это метод ГЕТ - простой вывод формы
    $this->_vid->view('v/login.html', array('errorMessage' => $this->_errorMessage, 'login' => $login));

    //parent::onEnd();
  }

}